### ISSUE TITLE
mdbook 0.1.9 and 0.1.10 were yanked

### ISSUE THREAD

**Issue by parasyte** [hrektts/docker-mdbook#1]
Just noticed this on https://crates.io/crates/mdbook ... 0.1.9 and 0.1.10 were yanked as explain in https://github.com/rust-lang-nursery/mdBook/issues/746#issuecomment-410018300

Can you create a tag with 0.1.8 and move `latest` to 0.2.0?

**Comment by hrektts** [comment]
Thanks for your information. I created the tags and they can now be downloaded from Docker Hub.
